version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: MinMin123
      MYSQL_DATABASE: user_base
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql